baseURL = "https://www.jens.und.nikas.de/"
defaultContentLanguage = "de"
title = "Piffle-Paffle Wiffle-Waffle Podcast"
theme = "hallo"

[author]
    name = "Jens und Nikas Wiese"

[params]
    greeting = "Links"

    [[params.links]]
        icon = "spotify"
        title = "Podcast bei Spotify"
        url = "https://open.spotify.com/show/5bkojM6HVGiWwcKAGFqwL0"
    [[params.links]]
        icon = "apple"
        title = "Podcast bei Apple Podcasts"
        url = "https://podcasts.apple.com/de/podcast/piffle-paffle-wiffle-waffle-podcast/id1507539185?l=de"
    [[params.links]]
        icon = "google"
        title = "Podcast bei Google Podcasts"
        url = "https://podcasts.google.com/feed/aHR0cHM6Ly9wcHd3LnBvZGlnZWUuaW8vZmVlZC9tcDM"
    [[params.links]]
        icon = "soundcloud"
        title = "Wir bei Soundcloud"
        url = "https://soundcloud.com/ppww-podcast"
    [[params.links]]
        iconset = "fas"
        icon = "rss-square"
        title = "Podcast Feed"
        url = "https://ppww.podigee.io/feed/mp3"

    [params.special]
        title = ""
        url = ""

    [params.currentEpisode]
        title = "Männerabend und Pizza"

        [[params.currentEpisode.links]]
            title = "Spotify"
            url = "https://open.spotify.com/episode/08FtIkeMzONvg98OogJtgF"
        [[params.currentEpisode.links]]
            title = "Apple Podcasts"
            url = "https://podcasts.apple.com/us/podcast/m%C3%A4nnerabend-und-pizza/id1507539185?i=1000497607437"
        [[params.currentEpisode.links]]
            title = "Google Podcasts"
            url = "https://podcasts.google.com/feed/aHR0cHM6Ly9wcHd3LnBvZGlnZWUuaW8vZmVlZC9tcDM/episode/MzZjNDk3NDFlZjI4NWYyYTY3OGIwNTljNDhjYjBhNWM"
        [[params.currentEpisode.links]]
            title = "Deezer"
            url = "https://deezer.page.link/7A5M45rf1cNr4gAY7"

[params.colors]
    background = "black"
    foreground = "#edf7ff"
    hover = "orange"

