baseURL = "https://www.jens.und.nikas.de/"
defaultContentLanguage = "de"
title = "Piffle-Paffle Wiffle-Waffle Podcast"
theme = "hallo"

[author]
    name = "Jens und Nikas Wiese"

[params]
    greeting = "Links"

    [[params.links]]
        icon = "spotify"
        title = "Podcast bei Spotify"
        url = "https://open.spotify.com/show/5bkojM6HVGiWwcKAGFqwL0"
    [[params.links]]
        icon = "apple"
        title = "Podcast bei Apple Podcasts"
        url = "https://podcasts.apple.com/de/podcast/piffle-paffle-wiffle-waffle-podcast/id1507539185?l=de"
    [[params.links]]
        icon = "google"
        title = "Podcast bei Google Podcasts"
        url = "https://podcasts.google.com/feed/aHR0cHM6Ly9wcHd3LnBvZGlnZWUuaW8vZmVlZC9tcDM"
    [[params.links]]
        icon = "soundcloud"
        title = "Wir bei Soundcloud"
        url = "https://soundcloud.com/ppww-podcast"
    [[params.links]]
        iconset = "fas"
        icon = "rss-square"
        title = "Podcast Feed"
        url = "https://ppww.podigee.io/feed/mp3"

    [params.currentEpisode]
        title = "Das Duell der Battle-Wraps"

        [[params.currentEpisode.links]]
            title = "Spotify"
            url = "https://open.spotify.com/episode/7IOgAElq1atHRsvkjL09V1"
        [[params.currentEpisode.links]]
            title = "Apple Podcasts"
            url = "https://podcasts.apple.com/de/podcast/piffle-paffle-wiffle-waffle-podcast/id1507539185?l=en#episodeGuid=1e53a516856eb8b16ca784e131761984"
        [[params.currentEpisode.links]]
            title = "Google Podcasts"
            url = "https://podcasts.google.com/feed/aHR0cHM6Ly9wcHd3LnBvZGlnZWUuaW8vZmVlZC9tcDM/episode/MWU1M2E1MTY4NTZlYjhiMTZjYTc4NGUxMzE3NjE5ODQ"
        [[params.currentEpisode.links]]
            title = "Deezer"
            url = "https://deezer.page.link/t4Hbi1JG3eBhHkah9"

[params.colors]
    background = "black"
    foreground = "#edf7ff"
    hover = "orange"

