baseURL = "https://www.jens.und.nikas.de/"
defaultContentLanguage = "de"
title = "Piffle-Paffle Wiffle-Waffle Podcast"
theme = "hallo"

[author]
    name = "Jens und Nikas Wiese"

[params]
    greeting = "Links"

    [[params.links]]
        icon = "spotify"
        title = "Podcast bei Spotify"
        url = "https://open.spotify.com/show/5bkojM6HVGiWwcKAGFqwL0"
    [[params.links]]
        icon = "apple"
        title = "Podcast bei Apple Podcasts"
        url = "https://podcasts.apple.com/de/podcast/piffle-paffle-wiffle-waffle-podcast/id1507539185?l=de"
    [[params.links]]
        icon = "google"
        title = "Podcast bei Google Podcasts"
        url = "https://podcasts.google.com/feed/aHR0cHM6Ly9wcHd3LnBvZGlnZWUuaW8vZmVlZC9tcDM"
    [[params.links]]
        icon = "soundcloud"
        title = "Wir bei Soundcloud"
        url = "https://soundcloud.com/ppww-podcast"
    [[params.links]]
        iconset = "fas"
        icon = "rss-square"
        title = "Podcast Feed"
        url = "https://ppww.podigee.io/feed/mp3"

    [params.special]
        title = "Etwas verspätet, aber sehr sehr gut: Unser Weihnachtsong"
        url = "https://soundcloud.com/ppww-podcast/let-it-snow-2020/s-Ecl2rpJffU7"

    [params.currentEpisode]
        title = "Weihnachtsferien im Escape-Room"

        [[params.currentEpisode.links]]
            title = "Spotify"
            url = "https://open.spotify.com/episode/37PmqBB2fgRGhZsyH43ozn"
        [[params.currentEpisode.links]]
            title = "Apple Podcasts"
            url = "https://podcasts.apple.com/de/podcast/piffle-paffle-wiffle-waffle-podcast/id1507539185?l=en#episodeGuid=95d03714bf26e5a1723824d9161297d4"
        [[params.currentEpisode.links]]
            title = "Google Podcasts"
            url = "https://podcasts.google.com/feed/aHR0cHM6Ly9wcHd3LnBvZGlnZWUuaW8vZmVlZC9tcDM/episode/OTVkMDM3MTRiZjI2ZTVhMTcyMzgyNGQ5MTYxMjk3ZDQ"
        [[params.currentEpisode.links]]
            title = "Deezer"
            url = "https://deezer.page.link/NgQp3jeDDzVwhkKi6"

[params.colors]
    background = "black"
    foreground = "#edf7ff"
    hover = "orange"

